name: nightly-index-publish

on:
  schedule:
    - cron: '0 19 * * *'     # 12:30 AM IST
    - cron: '30 7 * * *'     # 1:00 PM IST
    - cron: '30 13 * * *'    # 7:00 PM IST
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          persist-credentials: true

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install axios cheerio
      - run: node updatemyIndex.js              # writes docs/myIndex.json

      - name: "Debug: git status"
        run: git status

      - name: "Debug: git diff"
        run: git diff

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/myIndex.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update index via Action"
            git push origin gh-pages
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
